### ISSUE TITLE
Does it really need this indentation level

### ISSUE THREAD

**Issue by megawubs** [markwalet/laravel-changelog#2]
In the config, the level of nesting could be pulled one up by removing the `driver` key and just use `text => TextChangelogFormatter::class` as there are no other keys in the `text` array.

https://github.com/markwalet/laravel-changelog/blob/88235ac380d5a929dcebf82c16866b52658fb223/config/changelog.php#L46

**Comment by markwalet** [comment]
I personally like it this way. I'm passing the full configuration array to the constructor of a formatter. This makes it more future proof when people want to add their own formatters with more options.

Instead of migrating in a later version (With a breaking change), I decided to do it now already.

**Comment by megawubs** [comment]
True
